

BEGIN TRY

DECLARE @DATA nvarchar(max)  = convert(nvarchar(max),'')+concat(convert(nvarchar(max),''),N'
[{
	"ObjectName":"Contract_Supplement",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"Counter",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"(Counters.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanViewCollection":true,
	"ViewFilterCollection":"(Counters.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"Counters_Line",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"DeleteFilter":"Counters_Lines.BagId IS NULL AND Counters_Lines.IdDocAssistence IS NULL AND Counters_Lines.RegId IS NULL ",
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"Document_Object",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_AccessPoints_Skin",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"EditFilter":"(OriginId <> 1)",
	"CanDelete":true,
	"DeleteFilter":"(OriginId <> 1)",
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Board_Type",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Calendar",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_contract_hour_attribute",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Contract_Period",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Course",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Course_Program",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Courses_Assistant",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"(Courses_Assistants.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanViewCollection":true,
	"ViewFilterCollection":"(Courses_Assistants.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanInsert":true,
	"CanEdit":true,
	"EditFilter":"(Courses_Assistants.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanDelete":true,
	"DeleteFilter":"(Courses_Assistants.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Courses_Category",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Courses_Folder",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Courses_TimeTable",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Documents_Category",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Employee",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"((Employees.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))) OR Employees.EmployeeId = {{CurrentReference}}",
	"CanViewCollection":true,
	"ViewFilterCollection":"((Employees.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))) OR Employees.EmployeeId = {{CurrentReference}}",
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"DeleteFilter":"Employees.EmployeeId NOT IN (SELECT distinct EmployeeId FROM Employees_ContractData)",
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_employee_bankAccount",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Employee_ContractData",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"(Employees_ContractData.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanViewCollection":true,
	"ViewFilterCollection":"(Employees_ContractData.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanInsert":true,
	"CanEdit":true,
	"EditFilter":"(Employees_ContractData.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanDelete":true,
	"DeleteFilter":"(Employees_ContractData.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Employee_ContractData_ModHistory",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Employee_Experience",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Employee_Holiday",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"(Employees_Holidays.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanViewCollection":true,
	"ViewFilterCollection":"(Employees_Holidays.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanInsert":true,
	"CanEdit":true,
	"EditFilter":"(Employees_Holidays.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanDelete":true,
	"DeleteFilter":"(Employees_Holidays.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Employee_Holiday_Total",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Employee_Leave",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Employee_Shift_Period",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Employee_Study",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_EmployeePersonalData",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Employees_Groups_Historic",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Employees_Language",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Employees_Rules_Period",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Gas_Type",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Group_Schedule",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Holiday_Total",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Holidays_Type",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Journeys_Balance",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Marking",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"(Markings.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanViewCollection":true,
	"ViewFilterCollection":"(Markings.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanInsert":true,
	"CanEdit":true,
	"EditFilter":"(Markings.Closed = 0)",
	"CanDelete":true,
	"DeleteFilter":"(Markings.Closed = 0 AND Markings.TerminalCode is null)",
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Markings_Pair",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":false,
	"CanEdit":true,
	"CanDelete":false,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Organizational_Unit",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Organizational_Units_Position",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Part_Expenses",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"(Part_Expenses.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanViewCollection":true,
	"ViewFilterCollection":"(Part_Expenses.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanInsert":true,
	"CanEdit":true,
	"EditFilter":"Part_Expenses.EmployeeId = ''{{CurrentReference}}'' AND Part_Expenses.StatusId = 0",
	"CanDelete":true,
	"DeleteFilter":"Part_Expenses.EmployeeId = ''{{CurrentReference}}'' AND Part_Expenses.StatusId = 0",
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Pattern",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"DeleteFilter":"Patterns.PatternId  not in (SELECT PatternId FROM Pattern_Schedule)",
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Pattern_Schedule",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"EditFilter":"StatusId = 0",
	"CanDelete":true,
	"DeleteFilter":"StatusId = 0",
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Payroll_Adjust",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Payroll_Advance",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_PayrollRun",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Performance_Evaluation",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"(Performance_Evaluations.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanViewCollection":true,
	"ViewFilterCollection":"(Performance_Evaluations.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanInsert":true,
	"CanEdit":true,
	"EditFilter":"(Performance_Evaluations.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanDelete":true,
	"DeleteFilter":"(Performance_Evaluations.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Request",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"(Requests.ReceiverEmployeeId={{currentReference}} OR Requests.InsertedBy={{currentReference}} OR (SELECT ResponsableId FROM Employees WHERE EmployeeId=CASE WHEN ReceiverEmployeeId IS NULL THEN Requests.InsertedBy ELSE ReceiverEmployeeId END)={{currentReference}}) AND ((Requests.ReceiverEmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}}))))",
	"CanViewCollection":true,
	"ViewFilterCollection":"(Requests.ReceiverEmployeeId={{currentReference}} OR Requests.InsertedBy={{currentReference}} OR (SELECT ResponsableId FROM Employees WHERE EmployeeId=CASE WHEN ReceiverEmployeeId IS NULL THEN Requests.InsertedBy ELSE ReceiverEmployeeId END)={{currentReference}}) AND ((Requests.ReceiverEmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}}))))",
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Request_Type",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Reserve",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Setting",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":false,
	"CanEdit":true,
	"CanDelete":false,
	"CanPrint":false,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Shift",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Suggestion_Mailbox",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"((Suggestions_Mailbox.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}}))) OR Suggestions_Mailbox.EmployeeId IS NULL)",
	"CanViewCollection":true,
	"ViewFilterCollection":"((Suggestions_Mailbox.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}}))) OR Suggestions_Mailbox.EmployeeId IS NULL)",
	"CanInsert":true,
	"CanEdit":true,
	"EditFilter":"((Suggestions_Mailbox.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}}))) OR Suggestions_Mailbox.EmployeeId IS NULL)",
	"CanDelete":true,
	"DeleteFilter":"((Suggestions_Mailbox.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}}))) OR Suggestions_Mailbox.EmployeeId IS NULL)",
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Suggestion_Mailbox_Like",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":false,
	"CanViewCollection":true,
	"CanInsert":false,
	"CanEdit":false,
	"CanDelete":false,
	"CanPrint":false,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Team",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-27T13:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Travel",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_Travel_Status",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_vHR_Employee",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"(vHR_Employee.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanViewCollection":true,
	"ViewFilterCollection":"(vHR_Employee.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanInsert":false,
	"CanEdit":false,
	"CanDelete":false,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"emp_vHR_Employee_Daydate",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"(vHR_Employee_Daydate.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanViewCollection":true,
	"ViewFilterCollection":"(vHR_Employee_Daydate.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanInsert":false,
	"CanEdit":false,
	"CanDelete":false,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"Employee_Device",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"Employees_Admonition",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"Garnishment",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"HR_Employees_ContractLite",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"hr_OvertimeRegister",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"(OvertimeRegister.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanViewCollection":true,
	"ViewFilterCollection":"(OvertimeRegister.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanInsert":true,
	"CanEdit":true,
	"EditFilter":"(OvertimeRegister.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanDelete":true,
	"DeleteFilter":"(OvertimeRegister.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"hr_vEmployee_Balance",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"Instance",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"(Instances.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanViewCollection":true,
	"ViewFilterCollection":"(Instances.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"DeleteFilter":"(Instances.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"Organizational_Units_Supervisor",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"PayrollRun_Employee",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"PERS_Notificacion",
	"RoleId":"users",
	"CanView":true,
	"ViewFilter":".PERS_Notificaciones.employeeid = ''{{currentReference}}''",
	"CanViewCollection":true,
	"ViewFilterCollection":".PERS_Notificaciones.employeeid = ''{{currentReference}}''",
	"CanInsert":false,
	"CanEdit":false,
	"CanDelete":false,
	"CanPrint":true,
	"flxInsertedBy":"unknown",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-27T11:13:00",
	"flxUpdatedDate":"2026-05-27T12:59:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"Quadrant_Contract",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"(Quadrants_Contracts.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanViewCollection":true,
	"ViewFilterCollection":"(Quadrants_Contracts.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"sysAbhSign_Object_Config",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"sysAbhSign_Object_Report_Config",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"sysObject",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"sysRole",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"CanInsert":true,
	"CanEdit":true,
	"EditFilter":"Instances_Types.OriginId>1",
	"CanDelete":true,
	"DeleteFilter":"Instances_Types.OriginId>1",
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"sysUser",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"CanViewCollection":true,
	"ViewFilterCollection":"AspNetUsers.Id not in (''0'',''1'')",
	"CanInsert":true,
	"CanEdit":true,
	"CanDelete":true,
	"CanPrint":true,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-27T11:24:00",
	"OriginAddonId":"Main",
	"OriginId":2
},{
	"ObjectName":"vContracts_CurrentData",
	"RoleId":"PERS_ADMIN_PROGECO",
	"CanView":true,
	"ViewFilter":"(vContracts_CurrentData.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanViewCollection":true,
	"ViewFilterCollection":"(vContracts_CurrentData.EmployeeId IN (SELECT EmployeeId FROM dbo.fACM_GetVisibleEmployeeTbl({{CurrentReference}})))",
	"CanInsert":false,
	"CanEdit":false,
	"CanDelete":false,
	"CanPrint":false,
	"flxInsertedBy":"admin",
	"flxUpdatedBy":"admin",
	"flxInsertedDate":"2026-05-25T15:07:00",
	"flxUpdatedDate":"2026-05-25T15:07:00",
	"OriginAddonId":"Main",
	"OriginId":2}]')


MERGE INTO [Security_Objects_Roles] AS Target
USING ( 
SELECT * from OPENJSON(@DATA) WITH (
[ObjectName] nvarchar(50) '$.ObjectName'
,[RoleId] nvarchar(128) '$.RoleId'
,[CanView] bit '$.CanView'
,[ViewFilter] nvarchar(2048) '$.ViewFilter'
,[CanViewCollection] bit '$.CanViewCollection'
,[ViewFilterCollection] nvarchar(2048) '$.ViewFilterCollection'
,[CanInsert] bit '$.CanInsert'
,[InsertFilter] nvarchar(2048) '$.InsertFilter'
,[CanEdit] bit '$.CanEdit'
,[EditFilter] nvarchar(2048) '$.EditFilter'
,[CanDelete] bit '$.CanDelete'
,[DeleteFilter] nvarchar(2048) '$.DeleteFilter'
,[CanPrint] bit '$.CanPrint'
,[flxInsertedBy] nvarchar(256) '$.flxInsertedBy'
,[flxUpdatedBy] nvarchar(256) '$.flxUpdatedBy'
,[flxInsertedDate] smalldatetime '$.flxInsertedDate'
,[flxUpdatedDate] smalldatetime '$.flxUpdatedDate'
,[OriginAddonId] nvarchar(256) '$.OriginAddonId'
,[OriginId] int '$.OriginId'
) 
) AS Source ([ObjectName],[RoleId],[CanView],[ViewFilter],[CanViewCollection],[ViewFilterCollection],[CanInsert],[InsertFilter],[CanEdit],[EditFilter],[CanDelete],[DeleteFilter],[CanPrint],[flxInsertedBy],[flxUpdatedBy],[flxInsertedDate],[flxUpdatedDate],[OriginAddonId],[OriginId])
ON (Target.[ObjectName] = Source.[ObjectName] AND Target.[RoleId] = Source.[RoleId])
WHEN MATCHED AND (
	NULLIF(Source.[CanView], Target.[CanView]) IS NOT NULL OR NULLIF(Target.[CanView], Source.[CanView]) IS NOT NULL OR 
	NULLIF(Source.[ViewFilter], Target.[ViewFilter]) IS NOT NULL OR NULLIF(Target.[ViewFilter], Source.[ViewFilter]) IS NOT NULL OR 
	NULLIF(Source.[CanViewCollection], Target.[CanViewCollection]) IS NOT NULL OR NULLIF(Target.[CanViewCollection], Source.[CanViewCollection]) IS NOT NULL OR 
	NULLIF(Source.[ViewFilterCollection], Target.[ViewFilterCollection]) IS NOT NULL OR NULLIF(Target.[ViewFilterCollection], Source.[ViewFilterCollection]) IS NOT NULL OR 
	NULLIF(Source.[CanInsert], Target.[CanInsert]) IS NOT NULL OR NULLIF(Target.[CanInsert], Source.[CanInsert]) IS NOT NULL OR 
	NULLIF(Source.[InsertFilter], Target.[InsertFilter]) IS NOT NULL OR NULLIF(Target.[InsertFilter], Source.[InsertFilter]) IS NOT NULL OR 
	NULLIF(Source.[CanEdit], Target.[CanEdit]) IS NOT NULL OR NULLIF(Target.[CanEdit], Source.[CanEdit]) IS NOT NULL OR 
	NULLIF(Source.[EditFilter], Target.[EditFilter]) IS NOT NULL OR NULLIF(Target.[EditFilter], Source.[EditFilter]) IS NOT NULL OR 
	NULLIF(Source.[CanDelete], Target.[CanDelete]) IS NOT NULL OR NULLIF(Target.[CanDelete], Source.[CanDelete]) IS NOT NULL OR 
	NULLIF(Source.[DeleteFilter], Target.[DeleteFilter]) IS NOT NULL OR NULLIF(Target.[DeleteFilter], Source.[DeleteFilter]) IS NOT NULL OR 
	NULLIF(Source.[CanPrint], Target.[CanPrint]) IS NOT NULL OR NULLIF(Target.[CanPrint], Source.[CanPrint]) IS NOT NULL OR 
	NULLIF(Source.[flxInsertedBy], Target.[flxInsertedBy]) IS NOT NULL OR NULLIF(Target.[flxInsertedBy], Source.[flxInsertedBy]) IS NOT NULL OR 
	NULLIF(Source.[flxUpdatedBy], Target.[flxUpdatedBy]) IS NOT NULL OR NULLIF(Target.[flxUpdatedBy], Source.[flxUpdatedBy]) IS NOT NULL OR 
	NULLIF(Source.[flxInsertedDate], Target.[flxInsertedDate]) IS NOT NULL OR NULLIF(Target.[flxInsertedDate], Source.[flxInsertedDate]) IS NOT NULL OR 
	NULLIF(Source.[flxUpdatedDate], Target.[flxUpdatedDate]) IS NOT NULL OR NULLIF(Target.[flxUpdatedDate], Source.[flxUpdatedDate]) IS NOT NULL OR 
	NULLIF(Source.[OriginAddonId], Target.[OriginAddonId]) IS NOT NULL OR NULLIF(Target.[OriginAddonId], Source.[OriginAddonId]) IS NOT NULL OR 
	NULLIF(Source.[OriginId], Target.[OriginId]) IS NOT NULL OR NULLIF(Target.[OriginId], Source.[OriginId]) IS NOT NULL) THEN
 UPDATE SET
  [CanView] = Source.[CanView], 
  [ViewFilter] = Source.[ViewFilter], 
  [CanViewCollection] = Source.[CanViewCollection], 
  [ViewFilterCollection] = Source.[ViewFilterCollection], 
  [CanInsert] = Source.[CanInsert], 
  [InsertFilter] = Source.[InsertFilter], 
  [CanEdit] = Source.[CanEdit], 
  [EditFilter] = Source.[EditFilter], 
  [CanDelete] = Source.[CanDelete], 
  [DeleteFilter] = Source.[DeleteFilter], 
  [CanPrint] = Source.[CanPrint], 
  [flxInsertedBy] = Source.[flxInsertedBy], 
  [flxUpdatedBy] = Source.[flxUpdatedBy], 
  [flxInsertedDate] = Source.[flxInsertedDate], 
  [flxUpdatedDate] = Source.[flxUpdatedDate], 
  [OriginAddonId] = Source.[OriginAddonId], 
  [OriginId] = Source.[OriginId]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([ObjectName],[RoleId],[CanView],[ViewFilter],[CanViewCollection],[ViewFilterCollection],[CanInsert],[InsertFilter],[CanEdit],[EditFilter],[CanDelete],[DeleteFilter],[CanPrint],[flxInsertedBy],[flxUpdatedBy],[flxInsertedDate],[flxUpdatedDate],[OriginAddonId],[OriginId])
 VALUES(Source.[ObjectName],Source.[RoleId],Source.[CanView],Source.[ViewFilter],Source.[CanViewCollection],Source.[ViewFilterCollection],Source.[CanInsert],Source.[InsertFilter],Source.[CanEdit],Source.[EditFilter],Source.[CanDelete],Source.[DeleteFilter],Source.[CanPrint],Source.[flxInsertedBy],Source.[flxUpdatedBy],Source.[flxInsertedDate],Source.[flxUpdatedDate],Source.[OriginAddonId],Source.[OriginId])
WHEN NOT MATCHED BY SOURCE AND TARGET.OriginId = 2 THEN 
 DELETE
;
END TRY
BEGIN CATCH
    DECLARE @ERRORNUMBER	INT,@ERRORMSG		VARCHAR(MAX),@ERRORSTATE		INT
    SELECT @ERRORNUMBER = 50000 + ERROR_NUMBER(),@ERRORMSG = ERROR_MESSAGE(), @ERRORSTATE = ERROR_STATE();
    THROW @ERRORNUMBER, @ERRORMSG, @ERRORSTATE
END CATCH
GO





