//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEBASTIAN_PROGECO_VS.web_service_spec {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSContainer", Namespace="http://schemas.datacontract.org/2004/07/HTTPServers.WCFWebServer.WebServices")]
    public enum WSContainer : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cycle = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Calendar = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Shift = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimeType = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Zone = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Terminal = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Employee = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Message = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimeSlot = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResultTemplate = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FilterTemplate = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StructureTree = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Result = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Arithmetic = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActionGroup = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActionCalendar = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Planning = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Parent = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Settings = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimeTypeType = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InconsistencyType = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConTypeMessage = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResultType = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reader = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Card = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BreakMethod = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Menu = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sex = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConType = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alarm = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Module = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EventType = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fields = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemResult = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InconsistencyResult = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FieldView = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sessions = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TerminalStatus = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimeZone = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Door = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Device = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeviceConnector = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeviceType = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DetectedTerminal = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Action = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MessageDirection = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManualTransfer = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransferSource = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HorizontalAlign = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Chart = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Custom = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlarmDefs = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Primavera = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Falta = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VisitState = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExportTemplate = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlarmInstance = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EventAction = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PermissionTemplate = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activators = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActivatorsUse = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScheduledTasks = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorkActivity = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorkOrder = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EventTask = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WAPlannings = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WOPlannings = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InfoTask = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTemplate = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Visit = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VisitCard = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Report = 120,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSElement", Namespace="http://schemas.datacontract.org/2004/07/HTTPServers.WCFWebServer.WebServices")]
    [System.SerializableAttribute()]
    public partial class WSElement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/HTTPServers.WCFWebServer.WebServices")]
    [System.SerializableAttribute()]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ValuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Values {
            get {
                return this.ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuesField, value) != true)) {
                    this.ValuesField = value;
                    this.RaisePropertyChanged("Values");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClockingType", Namespace="http://schemas.datacontract.org/2004/07/HTTPServers.WCFWebServer.WebServices")]
    public enum ClockingType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Attendance = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Access = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Visit = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SDK = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clocking", Namespace="http://schemas.datacontract.org/2004/07/HTTPServers.WCFWebServer.WebServices")]
    [System.SerializableAttribute()]
    public partial class Clocking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClockingTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClockingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmployerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdReaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTerminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTimeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllDay {
            get {
                return this.AllDayField;
            }
            set {
                if ((this.AllDayField.Equals(value) != true)) {
                    this.AllDayField = value;
                    this.RaisePropertyChanged("AllDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClockingType {
            get {
                return this.ClockingTypeField;
            }
            set {
                if ((this.ClockingTypeField.Equals(value) != true)) {
                    this.ClockingTypeField = value;
                    this.RaisePropertyChanged("ClockingType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Datetime {
            get {
                return this.DatetimeField;
            }
            set {
                if ((this.DatetimeField.Equals(value) != true)) {
                    this.DatetimeField = value;
                    this.RaisePropertyChanged("Datetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdClocking {
            get {
                return this.IdClockingField;
            }
            set {
                if ((this.IdClockingField.Equals(value) != true)) {
                    this.IdClockingField = value;
                    this.RaisePropertyChanged("IdClocking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmployer {
            get {
                return this.IdEmployerField;
            }
            set {
                if ((this.IdEmployerField.Equals(value) != true)) {
                    this.IdEmployerField = value;
                    this.RaisePropertyChanged("IdEmployer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReader {
            get {
                return this.IdReaderField;
            }
            set {
                if ((this.IdReaderField.Equals(value) != true)) {
                    this.IdReaderField = value;
                    this.RaisePropertyChanged("IdReader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTerminal {
            get {
                return this.IdTerminalField;
            }
            set {
                if ((this.IdTerminalField.Equals(value) != true)) {
                    this.IdTerminalField = value;
                    this.RaisePropertyChanged("IdTerminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTimeType {
            get {
                return this.IdTimeTypeField;
            }
            set {
                if ((this.IdTimeTypeField.Equals(value) != true)) {
                    this.IdTimeTypeField = value;
                    this.RaisePropertyChanged("IdTimeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdZone {
            get {
                return this.IdZoneField;
            }
            set {
                if ((this.IdZoneField.Equals(value) != true)) {
                    this.IdZoneField = value;
                    this.RaisePropertyChanged("IdZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="web_service_spec.IWebServiceContract")]
    public interface IWebServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/List", ReplyAction="http://tempuri.org/IWebServiceContract/ListResponse")]
        SEBASTIAN_PROGECO_VS.web_service_spec.WSElement List(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/List", ReplyAction="http://tempuri.org/IWebServiceContract/ListResponse")]
        System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> ListAsync(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/ListFields", ReplyAction="http://tempuri.org/IWebServiceContract/ListFieldsResponse")]
        SEBASTIAN_PROGECO_VS.web_service_spec.WSElement ListFields(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, string[] fields, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/ListFields", ReplyAction="http://tempuri.org/IWebServiceContract/ListFieldsResponse")]
        System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> ListFieldsAsync(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, string[] fields, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/Get", ReplyAction="http://tempuri.org/IWebServiceContract/GetResponse")]
        SEBASTIAN_PROGECO_VS.web_service_spec.WSElement Get(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/Get", ReplyAction="http://tempuri.org/IWebServiceContract/GetResponse")]
        System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> GetAsync(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/GetFields", ReplyAction="http://tempuri.org/IWebServiceContract/GetFieldsResponse")]
        SEBASTIAN_PROGECO_VS.web_service_spec.WSElement GetFields(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, int id, string[] fields);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/GetFields", ReplyAction="http://tempuri.org/IWebServiceContract/GetFieldsResponse")]
        System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> GetFieldsAsync(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, int id, string[] fields);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/Set", ReplyAction="http://tempuri.org/IWebServiceContract/SetResponse")]
        int Set(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, SEBASTIAN_PROGECO_VS.web_service_spec.WSElement element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/Set", ReplyAction="http://tempuri.org/IWebServiceContract/SetResponse")]
        System.Threading.Tasks.Task<int> SetAsync(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, SEBASTIAN_PROGECO_VS.web_service_spec.WSElement element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/Delete", ReplyAction="http://tempuri.org/IWebServiceContract/DeleteResponse")]
        bool Delete(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/Delete", ReplyAction="http://tempuri.org/IWebServiceContract/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/GetResults", ReplyAction="http://tempuri.org/IWebServiceContract/GetResultsResponse")]
        SEBASTIAN_PROGECO_VS.web_service_spec.WSElement GetResults(int employeeId, System.DateTime firstDate, System.DateTime lastDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/GetResults", ReplyAction="http://tempuri.org/IWebServiceContract/GetResultsResponse")]
        System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> GetResultsAsync(int employeeId, System.DateTime firstDate, System.DateTime lastDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/GetMinutes", ReplyAction="http://tempuri.org/IWebServiceContract/GetMinutesResponse")]
        SEBASTIAN_PROGECO_VS.web_service_spec.WSElement GetMinutes(int employeeId, System.DateTime firstDate, System.DateTime lastDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/GetMinutes", ReplyAction="http://tempuri.org/IWebServiceContract/GetMinutesResponse")]
        System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> GetMinutesAsync(int employeeId, System.DateTime firstDate, System.DateTime lastDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/Results", ReplyAction="http://tempuri.org/IWebServiceContract/ResultsResponse")]
        SEBASTIAN_PROGECO_VS.web_service_spec.Result[] Results(int employeeId, string type, System.DateTime firstDate, System.DateTime lastDate, string[] resultsNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/Results", ReplyAction="http://tempuri.org/IWebServiceContract/ResultsResponse")]
        System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.Result[]> ResultsAsync(int employeeId, string type, System.DateTime firstDate, System.DateTime lastDate, string[] resultsNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/Clockings", ReplyAction="http://tempuri.org/IWebServiceContract/ClockingsResponse")]
        SEBASTIAN_PROGECO_VS.web_service_spec.Clocking[] Clockings(int employeeId, System.DateTime firstDate, System.DateTime lastDate, SEBASTIAN_PROGECO_VS.web_service_spec.ClockingType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/Clockings", ReplyAction="http://tempuri.org/IWebServiceContract/ClockingsResponse")]
        System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.Clocking[]> ClockingsAsync(int employeeId, System.DateTime firstDate, System.DateTime lastDate, SEBASTIAN_PROGECO_VS.web_service_spec.ClockingType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/GetTimeSlot", ReplyAction="http://tempuri.org/IWebServiceContract/GetTimeSlotResponse")]
        SEBASTIAN_PROGECO_VS.web_service_spec.WSElement GetTimeSlot(int employeeId, int readerId, System.DateTime day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/GetTimeSlot", ReplyAction="http://tempuri.org/IWebServiceContract/GetTimeSlotResponse")]
        System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> GetTimeSlotAsync(int employeeId, int readerId, System.DateTime day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/SetTimeSlot", ReplyAction="http://tempuri.org/IWebServiceContract/SetTimeSlotResponse")]
        bool SetTimeSlot(int employeeId, System.DateTime startDay, System.DateTime endDay, int readerId, SEBASTIAN_PROGECO_VS.web_service_spec.WSElement timeSlots);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/SetTimeSlot", ReplyAction="http://tempuri.org/IWebServiceContract/SetTimeSlotResponse")]
        System.Threading.Tasks.Task<bool> SetTimeSlotAsync(int employeeId, System.DateTime startDay, System.DateTime endDay, int readerId, SEBASTIAN_PROGECO_VS.web_service_spec.WSElement timeSlots);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/AddPlanning", ReplyAction="http://tempuri.org/IWebServiceContract/AddPlanningResponse")]
        bool AddPlanning(int employeeId, string planningName, bool allDay, int startMinute, int endMinute, int timeTypeId, System.DateTime[] dateInterval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/AddPlanning", ReplyAction="http://tempuri.org/IWebServiceContract/AddPlanningResponse")]
        System.Threading.Tasks.Task<bool> AddPlanningAsync(int employeeId, string planningName, bool allDay, int startMinute, int endMinute, int timeTypeId, System.DateTime[] dateInterval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/GetDateRange", ReplyAction="http://tempuri.org/IWebServiceContract/GetDateRangeResponse")]
        SEBASTIAN_PROGECO_VS.web_service_spec.WSElement GetDateRange(System.DateTime[] dateList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/GetDateRange", ReplyAction="http://tempuri.org/IWebServiceContract/GetDateRangeResponse")]
        System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> GetDateRangeAsync(System.DateTime[] dateList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/ServerInfo", ReplyAction="http://tempuri.org/IWebServiceContract/ServerInfoResponse")]
        SEBASTIAN_PROGECO_VS.web_service_spec.WSElement ServerInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceContract/ServerInfo", ReplyAction="http://tempuri.org/IWebServiceContract/ServerInfoResponse")]
        System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> ServerInfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebServiceContractChannel : SEBASTIAN_PROGECO_VS.web_service_spec.IWebServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceContractClient : System.ServiceModel.ClientBase<SEBASTIAN_PROGECO_VS.web_service_spec.IWebServiceContract>, SEBASTIAN_PROGECO_VS.web_service_spec.IWebServiceContract {
        
        public WebServiceContractClient() {
        }
        
        public WebServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SEBASTIAN_PROGECO_VS.web_service_spec.WSElement List(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container) {
            return base.Channel.List(container);
        }
        
        public System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> ListAsync(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container) {
            return base.Channel.ListAsync(container);
        }
        
        public SEBASTIAN_PROGECO_VS.web_service_spec.WSElement ListFields(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, string[] fields, string filter) {
            return base.Channel.ListFields(container, fields, filter);
        }
        
        public System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> ListFieldsAsync(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, string[] fields, string filter) {
            return base.Channel.ListFieldsAsync(container, fields, filter);
        }
        
        public SEBASTIAN_PROGECO_VS.web_service_spec.WSElement Get(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, int id) {
            return base.Channel.Get(container, id);
        }
        
        public System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> GetAsync(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, int id) {
            return base.Channel.GetAsync(container, id);
        }
        
        public SEBASTIAN_PROGECO_VS.web_service_spec.WSElement GetFields(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, int id, string[] fields) {
            return base.Channel.GetFields(container, id, fields);
        }
        
        public System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> GetFieldsAsync(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, int id, string[] fields) {
            return base.Channel.GetFieldsAsync(container, id, fields);
        }
        
        public int Set(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, SEBASTIAN_PROGECO_VS.web_service_spec.WSElement element) {
            return base.Channel.Set(container, element);
        }
        
        public System.Threading.Tasks.Task<int> SetAsync(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, SEBASTIAN_PROGECO_VS.web_service_spec.WSElement element) {
            return base.Channel.SetAsync(container, element);
        }
        
        public bool Delete(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, int id) {
            return base.Channel.Delete(container, id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(SEBASTIAN_PROGECO_VS.web_service_spec.WSContainer container, int id) {
            return base.Channel.DeleteAsync(container, id);
        }
        
        public SEBASTIAN_PROGECO_VS.web_service_spec.WSElement GetResults(int employeeId, System.DateTime firstDate, System.DateTime lastDate) {
            return base.Channel.GetResults(employeeId, firstDate, lastDate);
        }
        
        public System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> GetResultsAsync(int employeeId, System.DateTime firstDate, System.DateTime lastDate) {
            return base.Channel.GetResultsAsync(employeeId, firstDate, lastDate);
        }
        
        public SEBASTIAN_PROGECO_VS.web_service_spec.WSElement GetMinutes(int employeeId, System.DateTime firstDate, System.DateTime lastDate) {
            return base.Channel.GetMinutes(employeeId, firstDate, lastDate);
        }
        
        public System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> GetMinutesAsync(int employeeId, System.DateTime firstDate, System.DateTime lastDate) {
            return base.Channel.GetMinutesAsync(employeeId, firstDate, lastDate);
        }
        
        public SEBASTIAN_PROGECO_VS.web_service_spec.Result[] Results(int employeeId, string type, System.DateTime firstDate, System.DateTime lastDate, string[] resultsNames) {
            return base.Channel.Results(employeeId, type, firstDate, lastDate, resultsNames);
        }
        
        public System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.Result[]> ResultsAsync(int employeeId, string type, System.DateTime firstDate, System.DateTime lastDate, string[] resultsNames) {
            return base.Channel.ResultsAsync(employeeId, type, firstDate, lastDate, resultsNames);
        }
        
        public SEBASTIAN_PROGECO_VS.web_service_spec.Clocking[] Clockings(int employeeId, System.DateTime firstDate, System.DateTime lastDate, SEBASTIAN_PROGECO_VS.web_service_spec.ClockingType type) {
            return base.Channel.Clockings(employeeId, firstDate, lastDate, type);
        }
        
        public System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.Clocking[]> ClockingsAsync(int employeeId, System.DateTime firstDate, System.DateTime lastDate, SEBASTIAN_PROGECO_VS.web_service_spec.ClockingType type) {
            return base.Channel.ClockingsAsync(employeeId, firstDate, lastDate, type);
        }
        
        public SEBASTIAN_PROGECO_VS.web_service_spec.WSElement GetTimeSlot(int employeeId, int readerId, System.DateTime day) {
            return base.Channel.GetTimeSlot(employeeId, readerId, day);
        }
        
        public System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> GetTimeSlotAsync(int employeeId, int readerId, System.DateTime day) {
            return base.Channel.GetTimeSlotAsync(employeeId, readerId, day);
        }
        
        public bool SetTimeSlot(int employeeId, System.DateTime startDay, System.DateTime endDay, int readerId, SEBASTIAN_PROGECO_VS.web_service_spec.WSElement timeSlots) {
            return base.Channel.SetTimeSlot(employeeId, startDay, endDay, readerId, timeSlots);
        }
        
        public System.Threading.Tasks.Task<bool> SetTimeSlotAsync(int employeeId, System.DateTime startDay, System.DateTime endDay, int readerId, SEBASTIAN_PROGECO_VS.web_service_spec.WSElement timeSlots) {
            return base.Channel.SetTimeSlotAsync(employeeId, startDay, endDay, readerId, timeSlots);
        }
        
        public bool AddPlanning(int employeeId, string planningName, bool allDay, int startMinute, int endMinute, int timeTypeId, System.DateTime[] dateInterval) {
            return base.Channel.AddPlanning(employeeId, planningName, allDay, startMinute, endMinute, timeTypeId, dateInterval);
        }
        
        public System.Threading.Tasks.Task<bool> AddPlanningAsync(int employeeId, string planningName, bool allDay, int startMinute, int endMinute, int timeTypeId, System.DateTime[] dateInterval) {
            return base.Channel.AddPlanningAsync(employeeId, planningName, allDay, startMinute, endMinute, timeTypeId, dateInterval);
        }
        
        public SEBASTIAN_PROGECO_VS.web_service_spec.WSElement GetDateRange(System.DateTime[] dateList) {
            return base.Channel.GetDateRange(dateList);
        }
        
        public System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> GetDateRangeAsync(System.DateTime[] dateList) {
            return base.Channel.GetDateRangeAsync(dateList);
        }
        
        public SEBASTIAN_PROGECO_VS.web_service_spec.WSElement ServerInfo() {
            return base.Channel.ServerInfo();
        }
        
        public System.Threading.Tasks.Task<SEBASTIAN_PROGECO_VS.web_service_spec.WSElement> ServerInfoAsync() {
            return base.Channel.ServerInfoAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="web_service_spec.IClockingWebServiceContract")]
    public interface IClockingWebServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClockingWebServiceContract/SetClocking", ReplyAction="http://tempuri.org/IClockingWebServiceContract/SetClockingResponse")]
        bool SetClocking(SEBASTIAN_PROGECO_VS.web_service_spec.Clocking clocking);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClockingWebServiceContract/SetClocking", ReplyAction="http://tempuri.org/IClockingWebServiceContract/SetClockingResponse")]
        System.Threading.Tasks.Task<bool> SetClockingAsync(SEBASTIAN_PROGECO_VS.web_service_spec.Clocking clocking);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClockingWebServiceContractChannel : SEBASTIAN_PROGECO_VS.web_service_spec.IClockingWebServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClockingWebServiceContractClient : System.ServiceModel.ClientBase<SEBASTIAN_PROGECO_VS.web_service_spec.IClockingWebServiceContract>, SEBASTIAN_PROGECO_VS.web_service_spec.IClockingWebServiceContract {
        
        public ClockingWebServiceContractClient() {
        }
        
        public ClockingWebServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClockingWebServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClockingWebServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClockingWebServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SetClocking(SEBASTIAN_PROGECO_VS.web_service_spec.Clocking clocking) {
            return base.Channel.SetClocking(clocking);
        }
        
        public System.Threading.Tasks.Task<bool> SetClockingAsync(SEBASTIAN_PROGECO_VS.web_service_spec.Clocking clocking) {
            return base.Channel.SetClockingAsync(clocking);
        }
    }
}
