/**
 * @namespace flexygo.culture.caes
 */
declare namespace flexygo.culture.caes {
    const presences: {
        day: string;
        workingHours: string;
        absenceHours: string;
        workedHours: string;
        difference: string;
        nonBusinessDay: string;
        holidays: string;
        hours: string;
        days: string;
    };
    const warnings: {
        filterHolidays: string;
        removeHolidays: string;
    };
    const planner: {
        shifts: string;
        groups: string;
        employees: string;
        shift: string;
        group: string;
        employee: string;
        showdetails: string;
        showdraggables: string;
        today: string;
        week: string;
        month: string;
        absences: string;
        patterns: string;
        deleteplans: string;
        EmployeeSchedule: string;
        GroupSchedule: string;
        OfficePeriods: string;
        EmployeeRule0: string;
        EmployeePeriods: string;
        GroupScheduleFreeDay: string;
        PositionPeriods: string;
        UnitsPeriods: string;
        ScopePeriods: string;
        AssistenceShift: string;
    };
    const emp: {
        nocalendar: string;
        deletebtn: string;
        weeklyBtn: string;
        excelFileTitle: string;
        excelFileMsg: string;
        noItemsSelected: string;
        selectAtLeastOneEmployee: string;
        errorUpdatingShift: string;
        applyFilterToModifyBalances: string;
        selectCompanyGroupUnitAndDateRange: string;
        selectDateRange: string;
        cannotChangePlanificationStatus: string;
        existingMarkingsConfirm: string;
        cantUpdateSchedule: string;
        cannotModifyPastPlanification: string;
        employeeCreated: string;
        employeeCreatedHolidaysError: string;
        filterByDateRequired: string;
        instanceAbsences: string;
        instanceHolidays: string;
    };
    const balance: {
        year: string;
        month: string;
        week: string;
        back: string;
        foward: string;
    };
    const employeemanager: {
        employee: string;
        employeePersonal: string;
        employeeContract: string;
        employeeOrganization: string;
        save: string;
        next: string;
        exit: string;
        empmanagertitle: string;
    };
    const historiclst: {
        selectoption: string;
        selectoptionmsg: string;
    };
    const months: {
        1: string;
        2: string;
        3: string;
        4: string;
        5: string;
        6: string;
        7: string;
        8: string;
        9: string;
        10: string;
        11: string;
        12: string;
    };
    const weekdays: {
        mon: string;
        tue: string;
        wed: string;
        thu: string;
        fri: string;
        sat: string;
        sun: string;
    };
    const accesspoint: {
        errormsg: string;
        exit: string;
        enter: string;
        helloexit: string;
        helloenter: string;
        lastmarking: string;
        noplanning: string;
        employeeNotFound: string;
        accessIdNotFound: string;
    };
    const messages: {
        multipleabsencescalendar: string;
        markingsunplannedabsences: string;
        holidaysunplannedabsences: string;
    };
    const documents: {
        missingData: string;
        confirmDelete: string;
        deleteSuccess: string;
    };
    const incidences: {
        selectResolutionType: string;
        noResolutionType: string;
        noCurrentReference: string;
        incidencesResolved: string;
    };
    const workdays: {
        noWorkDaysSelected: string;
        workDaysValidated: string;
        noWorkDaysSelectedUndo: string;
        workDaysUnvalidated: string;
        noWorkDaysSelectedBalance: string;
        workDaysBalanced: string;
        noWorkDaysSelectedBalanceUndo: string;
        workDaysBalanceUndone: string;
        changeFestiveWorkedAllEmployeesConfirm: string;
        changeFestiveWorkedSuccess: string;
        refreshDayDateBatchConfirm: string;
        refreshAllDayDateBatchConfirm: string;
        changePlanificationAllDayDateBatchConfirm: string;
        changePlanificationWrapperBatchConfirm: string;
        changePlanificationWrapperBatchGroupedConfirm: string;
        noEmployeesSelectedCannotExecute: string;
        recalcMetricsDirtyBatchConfirm: string;
        recalcMetricsDirtyGroupedConfirm: string;
        recalcMetricsDirtySuccess: string;
        adminRecalcHistoryRangeConfirm: string;
        noHeaderDates: string;
        noModuleOrList: string;
        monthly: string;
        weekly: string;
    };
    const dirtylog: {
        calendar: string;
        date: string;
        description: string;
        view: string;
        type: string;
        datestart: string;
        dateend: string;
        reason: string;
        leavetype: string;
        shift: string;
        breaksigned: string;
        workonfestive: string;
        line: string;
        starttime: string;
        duration: string;
        hours: string;
    };
    const heatmap: {
        noData: string;
        less: string;
        more: string;
        date: string;
        healthScore: string;
        status: string;
        months: string;
        days: string;
    };
    const projects: {
        deleteweekplan: string;
    };
    const onlineapp: {
        welcome: string;
        goodbye: string;
    };
    const climatepulse: {
        good: string;
        neutral: string;
        difficult: string;
        send: string;
        thanks: string;
        'comment.placeholder': string;
    };
    const testdatawizard: {
        title: string;
        detecting: string;
        stepConfig: string;
        stepPreview: string;
        stepResult: string;
        restrictedTitle: string;
        restrictedMsg1: string;
        restrictedMsg2: string;
        backToHome: string;
        sectorLabel: string;
        sectorOffices: string;
        sectorManufacturing: string;
        sectorServices: string;
        volumeLabel: string;
        volumeHint: string;
        structureLabel: string;
        multiCompany: string;
        multiOffice: string;
        circuitsLabel: string;
        circuitOrg: string;
        circuitEmployees: string;
        circuitShifts: string;
        circuitAbsences: string;
        circuitMarkings: string;
        circuitContracts: string;
        next: string;
        previewTitle: string;
        previewDesc: string;
        previewSummary: string;
        previewSector: string;
        previewStructure: string;
        previewVolume: string;
        previewEmployeesEst: string;
        previewMode: string;
        previewDetails: string;
        timeEstimate: string;
        back: string;
        generate: string;
        generating: string;
        pleaseWait: string;
        successTitle: string;
        companies: string;
        offices: string;
        employees: string;
        historicYears: string;
        demoModeTitle: string;
        demoModeWarning: string;
        deleteData: string;
        finish: string;
        licensePrefix: string;
        testDataActive: string;
        generationComplete: string;
        confirmDelete: string;
        deletingData: string;
        errorGenerating: string;
        errorDeleting: string;
        detailsBase: string;
        detailsMarkings: string;
        detailsContracts: string;
        structureCompany: string;
        structureCompanies: string;
        structureOffice: string;
        structureOffices: string;
    };
}
