declare function empVote(): void;
declare function stopClickPropagation(element: any): void;
declare function setCalendarHtml(): void;
declare function changeIcon(): void;
declare function showDailyPresences(employeeId: any, year: any, month: any): void;
declare function showEquipment(elem: any, TypeId: any): void;
declare function showCollapsedEquipmentTypes(): void;
declare function flipCards(): void;
declare function schedulerInit(elem: any): void;
declare function colourFestives(elem: any): void;
declare function colourWeekends(): void;
declare function initGooglePlaces(): void;
declare function applyFormData(ret: any): void;
declare function initGoogleAutocomplete(): void;
declare function applyFormData2(ret2: any): void;
declare function formatIBAN(iban: any): string;
declare function initOrganizationalUnitModules(module: any, unitId: any, controlMode: any, unitName: any): void;
declare function OrgUnitListIsFiltered(elem: any): void;
declare function drawChildUnitsList(elem: any, parentUnitId: any, ChildUnits: any): void;
declare function setLastUnit(e: any): void;
declare function initOrganizationalUnitGroupEmployees(module: any, objWhere: any, e: any): void;
declare function initOrganizationalUnitAllEmployees(module: any, objWhere: any, e: any): void;
declare let control: string;
declare function paintCustomEditList(propInfo: any, selector: string, newBtn: boolean): void;
declare function paintCustomEditListRow(propInfo: any, newBtn: any): string;
declare function cloneEditListRow(e: any): void;
declare function removeEditListRow(e: any): void;
declare function selectShiftToClone(e: any): void;
declare function cloneShifts(UnitId: any, e: any): void;
declare function setButtonClone(e: any): void;
declare function setDateTitleDayliDB(element: any): void;
declare function setFillEmployeesCandidatePositions(el: any): string;
declare function goToOrgUnitList(elem: any, unitId: any, controlMode: any): void;
declare function assignScopeShift(element: any): void;
declare function enableShift(shiftId: number): void;
declare function enableGroup(groupId: number): void;
declare function checkCurrentJourney(currentJourneyId: number, rowJourneyId: number): string;
declare function initAppealEmployeesList(element: any, positionId: any, appealId: any): void;
declare function replaceUnitIds(element: any): void;
declare function initHRCalendar(element: any): void;
declare function filterCalendarByEmployee(employeeId: any, employeeName: any): void;
declare function initEmployeeSchedulePlanner(): void;
declare function filterEmployeeViewPage(element: any): void;
declare function initEmployeesIncidentsJourney(element: any): void;
declare function getEmployeeId(element: any): string;
declare function hideNewHolidayBtnCalendar(element: any): void;
declare function filterBalanceModules(elem: any): void;
declare function generateColors(): string;
declare function updatePatternShift(elem: any, patternId: any, patternShift: any): void;
declare function setShiftComboValue(elem: any, patternId: any, patternShift: any): any;
declare function selectPatternScheduleGroup(elem: any, cycleScheduleId: any, cycleId: any): void;
declare function selectPatternScheduleEmployee(elem: any, cycleScheduleId: any, cycleId: any): void;
declare function GetObjectWhereEmployeesPattern(): string;
declare function hideGroupPatternModule(): void;
declare function patternButtonEvent(element: any): void;
declare function EmployeesStandbyIDBatch(element: any, processname: any): void;
declare function OrganizationalUnitsPositionsIBatch(element: any): void;
declare function CountersEmployeesInitializeIBatch(element: any): void;
declare function CountersEmployeesInitializeIBatch_Lite(element: any): void;
declare function LocationControlRulesEmployeesInitializeIBatch(element: any): void;
declare function Employees_Add_Holidays_Periods_IBatch(element: any): void;
declare function EmployeesGroupsHistoricIBatch(elem: any): void;
declare function setAnswerButtons(type: string, idQuestion: string, RedId: number, value: string): string;
declare function updateAnswerResult(control: any): void;
declare function getBalanceListFilterFields_UpdateMasive(listId: any): void;
declare function getBalanceListFilterFields(listId: any): void;
declare function getMarkingsListFilterFields(listId: any): void;
declare function exportPayrollRunExcelWithFilters(listId: any, RunId: any): void;
declare function getComboAdditionalWhere(element: any): void;
declare function filterWorkingDayModulesByGroup(element: any, cleaning?: boolean): void;
declare function filterBalanceFullList(): void;
declare function filterModulesByGroup(element: any, modules: any, cleaning?: boolean): void;
declare function setAddtionalWhereGroupsManage(currentFilter: any): void;
declare function setMarkingsModulesAdditionalWhere(element: any, previewMod?: boolean): void;
declare function EmployeeStandbyIBatchGroup(element: any, groupId: any, currentReference: any): void;
declare function EmployeeStandbyDBatchGroup(element: any, groupId: any, currentReference: any): void;
declare function EmployeeWorkingDatRefresh(): void;
declare function GroupMarkingsAllManaged(element: any, groupId: any, currentReference: any): void;
declare function showBalanceTotals(element: any): void;
declare function initSettingsList(module: any, groupId: any, title: any): void;
declare function hideSettingList(module: any): void;
declare function AhoraIntegrationOptions(): void;
declare function CDIntegrationOptions(): void;
declare function EPmigration(): void;
declare function getLicense(): void;
declare function ApprovalFlow(module: any, groupId: any, title: any): void;
declare function updateApprovalFlowType(element: any, property: any, typeId: any): void;
declare function InsertAbscenceButtonHideControl(element: any): void;
declare function ChangeInstanceTypeOnPendings(module: any, TypeId: any): void;
declare function initInstanceModules(element: any, typeId: any): void;
declare function EmployeeMarkingsFilterDateAfterLoad(e: any): void;
declare function DaydateSummaryDetailsTitle(elem: any): void;
declare function markingsCheckBalanceButton(module: any): void;
declare function drawBalanceButton(module: any): void;
declare function overtimeRuleLines_Save(e: any): boolean;
declare function bagHoursLine_EnableEdit(e: any): void;
declare function bagHoursLine_changeHourType(e: any): void;
declare function bagHoursLine_Save(e: any): boolean;
declare function openTotalHolidaysSummaryCalendar(element: any, employeeId: any): void;
declare function filterPatternsList(element: any): void;
declare function plannerInsertAbsence(entity: any, groupId: any, plannerDate: any, triggerElement: any): void;
declare function plannerInsertEmployeeSchedule(entity: any, groupId: any, plannerDate: any, triggerElement: any): void;
declare function plannerInsertGroupSchedule(mode: any, entity: any, groupId: any, plannerDate: any, triggerElement: any): void;
declare function plannerMoveEmployeeSchedule(entity: any, groupId: any, plannerDate: any, triggerElement: any): void;
declare function cloneGroupSchedule(groupId: any, plannerDate: any, triggerElement: any, filterField: any): void;
declare function cloneEmployeeSchedules(groupId: any, plannerDate: any, triggerElement: any): void;
declare function DeleteEmployeeSchedules(groupId: any, plannerDate: any, triggerElement: any): void;
declare function filterOrganizationalUnitsPlannerFilter(element: any): void;
declare function toggleFestiveDayMarkings(element: any, DayDate: any, EmployeeId: any, markedAsFestive: any): void;
declare function fillEmployeesHolidaysFromEmployeeWizard(EmployeeId: any, roundHolidays: any): void;
declare function showSelectedRowsMarkings(elem: any): void;
declare function selectAllListRowsMarkings(modulename: any, moduleType: any, element: any): void;
declare function removeEmployeesHolidays(processname: any, objectname: any, objectwhere: any, targetid: any, excludeHist: any, triggerElement: any, currentProcess: any, eventData: any): void;
declare function viewReport_LibroRegistroJornada(element: any): void;
declare function EditEmployeesDocumentsSignerConfFormAfterLoad(): void;
declare function drawConfigureDocumentsSignerButton(module: any): void;
declare function filterHourAttributesList(elem: any, oWhere: any): void;
declare function filterHourAttributesListRemoveFilter(): void;
declare function paintHourAttributesListsRows(elem: any): void;
declare function documentsConfirmDeliveryShowButton(): void;
declare function GenerateAbsencePendingJustificationBatch(elem: any, DayDate: any): void;
declare function GenerateMarkingsAccordingToPlanning(elem: any, DayDate: any): void;
declare function addACMEmployeesBatch(element: any): void;
declare function removeACMEmployeesBatch(element: any): void;
declare function CoursesChangeStarsScore(elem: any, score: any): void;
declare const listFilters: {
    [key: string]: {
        categories: string[];
        textSearch: string | null;
    };
};
declare function filterEmployeeDocumentListByFolder(CategoryId: any, filteredListModuleName: any, elem: any): void;
declare function filterEmployeePageDocumentsList(elem: any): void;
declare function applyFilters(list: flexygo.ui.wc.FlxListElement, moduleName: string): void;
declare function restoreActiveCategoryStyles(moduleName: string): void;
declare function updateDocumentEmployeeIdNumber(regId: any, element: any): void;
declare function plannerAfterLoad(elem: any): void;
declare function filterPlannerResourcesDraggableList(element: any, cleaning: any): void;
declare function initAllDayDateDashboardList(element: any): void;
declare function setDoughnutChart(): void;
declare function deleteDocumentByGuid(element: any): void;
